# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }], azure_id: "")
#   Character.create(name: 'Luke', movie: movies.first, azure_id: "")

# rails db:seed -> add seed records to database

# Italian
Restaurant.create(name: "Casanova", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/casanova-santa-apol%C3%B3nia-lisboa", google_maps_url: "", azure_id: "1")
Restaurant.create(name: "Pizzeria Lucca", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/pizzeria-lucca-alvalade-lisboa", google_maps_url: "https://goo.gl/maps/Gs74snX4Pt2PTF5QA", azure_id: "2")
Restaurant.create(name: "Bellalisa Valmor", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/bellalisa-valmor-pra%C3%A7a-de-espanha-lisboa", google_maps_url: "", azure_id: "3")
Restaurant.create(name: "Popolo", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/popolo-pizza-burger-santos-lisboa", google_maps_url: "", azure_id: "4")
Restaurant.create(name: "Este Oeste", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/este-oeste-bel%C3%A9m-lisboa", google_maps_url: "", azure_id: "5")
Restaurant.create(name: "Guilty by Olivier", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/guiltybyolivier", google_maps_url: "", azure_id: "6")
Restaurant.create(name: "Pizzaria do bairro", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/pizzaria-do-bairro-cais-do-sodr%C3%A9-lisboa", google_maps_url: "", azure_id: "7")
Restaurant.create(name: "La Campania", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/la-campania-rato-lisboa", google_maps_url: "", azure_id: "8")
Restaurant.create(name: "La finestra", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/la-finestra-pra%C3%A7a-de-espanha-lisboa", google_maps_url: "", azure_id: "9")
Restaurant.create(name: "Capriciosa", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/capricciosa-alc%C3%A2ntara-lisboa", google_maps_url: "", azure_id: "10")
Restaurant.create(name: "Bellezza D'Italia II", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/bellezza-ditalia-ii-campo-pequeno-lisboa", google_maps_url: "", azure_id: "11")
Restaurant.create(name: "Zero Zero", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/zero-zero-pr%C3%ADncipe-real-pr%C3%ADncipe-real-lisboa", google_maps_url: "", azure_id: "12")
Restaurant.create(name: "La trattoria", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/la-trattoria-rato-lisboa", google_maps_url: "", azure_id: "13")
Restaurant.create(name: "Madpizza", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/madpizza-saldanha-lisboa", google_maps_url: "", azure_id: "14")
Restaurant.create(name: "Osteria cucina di amici", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/osteria-madragoa-lisboa", google_maps_url: "", azure_id: "15")
Restaurant.create(name: "Mercantina", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/mercantina-alvalade-lisboa", google_maps_url: "", azure_id: "16")
Restaurant.create(name: "Di casa", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/di-casa-areeiro-lisboa", google_maps_url: "", azure_id: "17")
Restaurant.create(name: "Luzzo", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/pizzaria-luzzo-avenida-da-liberdade-lisboa", google_maps_url: "", azure_id: "18")
Restaurant.create(name: "Máfia das pizzas", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/m%C3%A1fia-das-pizzas-cacilhas", google_maps_url: "", azure_id: "19")
Restaurant.create(name: "Pasta non basta", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/pasta-non-basta-pra%C3%A7a-de-espanha-lisboa", google_maps_url: "", azure_id: "20")
Restaurant.create(name: "Come prima", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/come-prima-lapa-estrela-lisboa", google_maps_url: "", azure_id: "21")
Restaurant.create(name: "Maritaca", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/maritaca-lapa-estrela-lisboa", google_maps_url: "", azure_id: "22")
Restaurant.create(name: "Otto", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/otto-2-cais-do-sodr%C3%A9-lisboa", google_maps_url: "", azure_id: "23")
Restaurant.create(name: "Casa Al Parma", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/casa-al-parma-alvalade-lisboa", google_maps_url: "", azure_id: "24")
Restaurant.create(name: "II Matriciano", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/il-matriciano-s%C3%A3o-bento-lisboa", google_maps_url: "", azure_id: "25")
Restaurant.create(name: "Polpetta - Almondegaria artesanal", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/polpetta-almondegaria-artesanal-arroios-lisboa", google_maps_url: "", azure_id: "26")
Restaurant.create(name: "Cantina baldraca", category: "Italian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/cantina-baldracca-mouraria-lisboa", google_maps_url: "", azure_id: "28")

# Hamburgers
Restaurant.create(name: "Honorato", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/honorato-chiado-lisboa", google_maps_url: "", azure_id: "31")
Restaurant.create(name: "Ground burguer", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/ground-burger-pra%C3%A7a-de-espanha-lisboa", google_maps_url: "", azure_id: "29")  
Restaurant.create(name: "Buns", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/buns-o-atelier-do-burger-rato-lisboa", google_maps_url: "", azure_id: "33")
Restaurant.create(name: "A-100 Burguer Delivery", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/a-100-burguer-delivery-campo-grande-lisboa", google_maps_url: "", azure_id: "34")
Restaurant.create(name: "To.B", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/to-b-chiado-lisboa", google_maps_url: "", azure_id: "35")
Restaurant.create(name: "Hamburgaria do Bairro", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/hamburgueria-do-bairro-restelo-lisboa", google_maps_url: "", azure_id: "36")
Restaurant.create(name: "McDonalds", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/mcdonalds-restelo", google_maps_url: "", azure_id: "37")
Restaurant.create(name: "Café do Rio (gourmet)", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/caf%C3%A9-do-rio-hamburgueria-gourmet-baixa-lisboa", google_maps_url: "", azure_id: "38")
Restaurant.create(name: "B Perfect", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/b-perfect-areeiro-lisboa", google_maps_url: "", azure_id: "39")
Restaurant.create(name: "The B Temple", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/the-b-temple-chiado-lisboa", google_maps_url: "", azure_id: "40")
Restaurant.create(name: "Hã", category: "Hamburgers", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/h%C3%A3-campo-pequeno-lisboa", google_maps_url: "", azure_id: "41")

# Sushi
Restaurant.create(name: "Sushisan", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/sushisan-saldanha-lisboa", google_maps_url: "", azure_id: "44")
Restaurant.create(name: "Suntory", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/suntory-campolide-lisboa", google_maps_url: "", azure_id: "45")
Restaurant.create(name: "Aron sushi", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/aron-sushi-pra%C3%A7a-de-espanha-lisboa", google_maps_url: "", azure_id: "46")
Restaurant.create(name: "Rabo d'Pêxe", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/rabo-dp%C3%AAxe-saldanha-lisboa", google_maps_url: "", azure_id: "47")
Restaurant.create(name: "Sea me", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/sea-me-peixaria-moderna-chiado-lisboa", google_maps_url: "", azure_id: "48")
Restaurant.create(name: "Sushi factory", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/sushi-factory-alc%C3%A2ntara-lisboa", google_maps_url: "", azure_id: "49")
Restaurant.create(name: "Confraria ", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/confraria-cascais-centro-lisboa", google_maps_url: "", azure_id: "50")
Restaurant.create(name: "Miss jappa", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/miss-jappa-pr%C3%ADncipe-real-lisboa", google_maps_url: "", azure_id: "51")
Restaurant.create(name: "Yakuza", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/yakuza-first-floor-rato-lisboa", google_maps_url: "", azure_id: "52")
Restaurant.create(name: "Sushic ", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/sushic-chiado-chiado-lisboa", google_maps_url: "", azure_id: "53")
Restaurant.create(name: "Noori Sushi", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/noori-sushi-benfica-lisboa/menu", google_maps_url: "", azure_id: "54")
Restaurant.create(name: "Kiuuby", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/kyuubi-oeiras-e-s%C3%A3o-juli%C3%A3o-da-barra-lisboa", google_maps_url: "", azure_id: "55")
Restaurant.create(name: "Nómada ", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/n%C3%B3mada-campo-pequeno-lisboa", google_maps_url: "", azure_id: "56")
Restaurant.create(name: "Chirashi Sushi (bowls)", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/chirashi-telheiras-lisboa", google_maps_url: "", azure_id: "57")
Restaurant.create(name: "Avenida SushiCafé", category: "Sushi", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/avenida-sushicaf%C3%A9-avenida-da-liberdade-lisboa", google_maps_url: "", azure_id: "58")

# Asian
Restaurant.create(name: "SOI", category: "Asian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/soi-cais-do-sodr%C3%A9-lisboa", google_maps_url: "", azure_id: "61")
Restaurant.create(name: "O Asiático", category: "Asian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/o-asitico-pr%C3%ADncipe-real", google_maps_url: "", azure_id: "62")
Restaurant.create(name: "BOA BAO", category: "Asian", price_range: 1, zomato_url: "", google_maps_url: "https://www.zomato.com/pt/boabao", azure_id: "63")
Restaurant.create(name: "Tasquinha dim sum", category: "Asian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/tasquinha-dim-sum-s%C3%A3o-bento-lisboa", google_maps_url: "", azure_id: "64")
Restaurant.create(name: "Siam Square (Thai)", category: "Asian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/siam-square-saldanha-lisboa", google_maps_url: "", azure_id: "65")
Restaurant.create(name: "Pho-Pu (Vietnamise)", category: "Asian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/pho-pu-mouraria-lisboa", google_maps_url: "", azure_id: "66")
Restaurant.create(name: "Este Oeste", category: "Asian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/este-oeste-bel%C3%A9m-lisboa", google_maps_url: "", azure_id: "67")

# Indian
Restaurant.create(name: "Chutnify Lisbon", category: "Indian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/chutnify-pr%C3%ADncipe-real-pr%C3%ADncipe-real-lisboa", google_maps_url: "", azure_id: "70")
Restaurant.create(name: "Kaprixu", category: "Indian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/kaprixu-telheiras-lisboa", google_maps_url: "", azure_id: "71")
Restaurant.create(name: "Soão - Taberna Asiática", category: "Indian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/so%C3%A3o-taberna-asi%C3%A1tica-alvalade-lisboa", google_maps_url: "", azure_id: "72")
Restaurant.create(name: "India gate (Chiado)", category: "Indian", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/india-gate-s%C3%A9-lisboa", google_maps_url: "", azure_id: "73")

# Seafood
Restaurant.create(name: "Rabo d'Pêxe", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/rabo-dp%C3%AAxe-saldanha-lisboa", google_maps_url: "", azure_id: "47")
Restaurant.create(name: "Monte mar", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/grande-lisboa/monte-mar-lisboa-cais-do-sodr%C3%A9-lisboa", google_maps_url: "", azure_id: "77")
Restaurant.create(name: "Sea me", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/sea-me-peixaria-moderna-chiado-lisboa", google_maps_url: "", azure_id: "48")
Restaurant.create(name: "Tasca da esquina", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/tasca-da-esquina-lapa-estrela-lisboa", google_maps_url: "", azure_id: "79")
Restaurant.create(name: "Pinóquio", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/cervejaria-pin%C3%B3quio-baixa-lisboa/menu", google_maps_url: "", azure_id: "80")
Restaurant.create(name: "tico tico", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/tico-tico-alvalade-lisboa", google_maps_url: "", azure_id: "81")
Restaurant.create(name: "Ramiro", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/ramiro-mouraria-lisboa", google_maps_url: "", azure_id: "82")
Restaurant.create(name: "Moules & Beer", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/MoulesBeer", google_maps_url: "", azure_id: "83")
Restaurant.create(name: "Peixaria da esquina", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/peixaria-da-esquina-campo-de-ourique-lisboa", google_maps_url: "", azure_id: "84")
Restaurant.create(name: "Doc Cod", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/doc-cod-alc%C3%A2ntara-lisboa", google_maps_url: "", azure_id: "85")
Restaurant.create(name: "Pesqueiro 25 (groups)", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/pesqueiro-25-cais-do-sodr%C3%A9-lisboa", google_maps_url: "", azure_id: "86")
Restaurant.create(name: "Pesca", category: "Seafood", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/pesca-pr%C3%ADncipe-real-lisboa", google_maps_url: "", azure_id: "87")

# Hotdogs
Restaurant.create(name: "Cachorraria Nacional", category: "Hotdogs", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/cachorraria-nacional-s%C3%A3o-bento-lisboa", google_maps_url: "", azure_id: "90")
Restaurant.create(name: "Frankie", category: "Hotdogs", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/frankie-hot-dogs-campo-grande-lisboa", google_maps_url: "", azure_id: "91")

# Tapas and snacks
Restaurant.create(name: "100 montaditos", category: "Tapas and Snacks", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/100-montaditos-campo-grande-lisboa", google_maps_url: "", azure_id: "94")
Restaurant.create(name: "Topo", category: "Tapas and Snacks", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/topo-mouraria-lisboa", google_maps_url: "", azure_id: "95")
Restaurant.create(name: "Cervejaria da esquina", category: "Tapas and Snacks", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/cervejaria-da-esquina-campo-de-ourique-lisboa", google_maps_url: "", azure_id: "96")
Restaurant.create(name: "Tapas bar", category: "Tapas and Snacks", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/tapas-bar-52-pr%C3%ADncipe-real-lisboa", google_maps_url: "", azure_id: "97")
Restaurant.create(name: "Rubro", category: "Tapas and Snacks", price_range: 1, zomato_url: "https://www.zomato.com/pt/grande-lisboa/rubro-campo-pequeno-lisboa", google_maps_url: "", azure_id: "98")
Restaurant.create(name: "Boteco do largo", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "99")
Restaurant.create(name: "Masstige", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "100")
Restaurant.create(name: "Mesa do bairro", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "101")
Restaurant.create(name: "By the wine", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "102")
Restaurant.create(name: "Pharmacia ", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "103")
Restaurant.create(name: "Matateu", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "104")
Restaurant.create(name: "Pateo do petisco (Cascais)", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "105")
Restaurant.create(name: "Luzboa ", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "106")
Restaurant.create(name: "Água pela Barba", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "107")
Restaurant.create(name: "Tapisco", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "108")
Restaurant.create(name: "Bairro do Avillez - Taberna", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "109")
Restaurant.create(name: "Mini Bar", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "110")
Restaurant.create(name: "Madame petisca", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "111")
Restaurant.create(name: "Vinhos e petiscos (costa)", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "112")
Restaurant.create(name: "Boteco do largo (jantares grupo)", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "113")
Restaurant.create(name: "Largo ao Tacho (fado as quartas)", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "114")
Restaurant.create(name: "Maria azeitona (Amadora)", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "115")
Restaurant.create(name: "Travessia Bar (Cacilhas)", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "116")
Restaurant.create(name: "NANA petiscos (Charnecas)", category: "Tapas and Snacks", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "117")

# Steak
Restaurant.create(name: "Atalho Real", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "120")
Restaurant.create(name: "Cafe império", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "121")
Restaurant.create(name: "Cafe de Sao bento", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "122")
Restaurant.create(name: "Grelhados alcantara", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "123")
Restaurant.create(name: "XL", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "124")
Restaurant.create(name: "Dote", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "125")
Restaurant.create(name: "Pito do bairro", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "126")
Restaurant.create(name: "Brasserie", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "127")
Restaurant.create(name: "O fondue", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "128")
Restaurant.create(name: "Terrazza", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "129")
Restaurant.create(name: "Butchers", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "130")
Restaurant.create(name: "Carnalentejana", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "131")
Restaurant.create(name: "O Talho", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "132")
Restaurant.create(name: "Kob", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "133")
Restaurant.create(name: "Volver de carne y alma", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "134")
Restaurant.create(name: "Carvoeiro de palma", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "135")
Restaurant.create(name: "Tasca Chiado naco", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "136")
Restaurant.create(name: "Adega das gravatas (carnide)", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "137")
Restaurant.create(name: "Nogueira’s", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "138")
Restaurant.create(name: "C.O.W - Beef & Cocktails", category: "Steak", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "139")

# Mexican
Restaurant.create(name: "El pibe", category: "Mexican", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "142")
Restaurant.create(name: "El clandestino", category: "Mexican", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "143")
Restaurant.create(name: "Las ficheras", category: "Mexican", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "144")
Restaurant.create(name: "Pistola y corazon", category: "Mexican", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "145")
Restaurant.create(name: "Segundo muelle", category: "Mexican", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "146")
Restaurant.create(name: "Cheviceria", category: "Mexican", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "147")
Restaurant.create(name: "Mez cais", category: "Mexican", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "148")
Restaurant.create(name: "Gazpaxo", category: "Mexican", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "149")

# Peruvian Nepalese
Restaurant.create(name: "Cevicheria", category: "Peruvian or Nepalese", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "152")
Restaurant.create(name: "Casa Nepalesa", category: "Peruvian or Nepalese", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "153")
Restaurant.create(name: "Cantina Peruana", category: "Peruvian or Nepalese", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "154")
Restaurant.create(name: "Segundo Muelle", category: "Peruvian or Nepalese", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "155")

# Brunch
Restaurant.create(name: "nicolau", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "158")
Restaurant.create(name: "fabrica dos sabores", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "159")
Restaurant.create(name: "brick cafe", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "160")
Restaurant.create(name: "O austriaco", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "161")
Restaurant.create(name: "Choupana", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "162")
Restaurant.create(name: "Brunch Cafe", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "163")
Restaurant.create(name: "The mill", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "164")
Restaurant.create(name: "Infame (almoço também)", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "165")
Restaurant.create(name: "O ninho - café brunch", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "166")
Restaurant.create(name: "Leitaria", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "167")
Restaurant.create(name: "Delidelux", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "168")
Restaurant.create(name: "Heim cafe", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "169")
Restaurant.create(name: "Dear Breakfast", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "170")
Restaurant.create(name: "Brooklyn", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "171")
Restaurant.create(name: "La Boulangerie", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "172")
Restaurant.create(name: "Santo Bagel", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "173")
Restaurant.create(name: "Pão Nosso de cada dia", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "174")
Restaurant.create(name: " Petit Prince Culture Cafe Lisbon", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "175")
Restaurant.create(name: "Mercearia da Mila", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "176")
Restaurant.create(name: "Ela canela", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "177")
Restaurant.create(name: "Maria Limão", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "178")
Restaurant.create(name: "WISH slow coffee house", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "179")
Restaurant.create(name: "fauna e flora", category: "Brunch", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "180")

# Icecreams & Sweets
Restaurant.create(name: "Conchanata", category: "Icecream and sweets", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "183")
Restaurant.create(name: "Baguettes & Cornets", category: "Icecream and sweets", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "184")
Restaurant.create(name: "Nosolo Italia", category: "Icecream and sweets", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "185")
Restaurant.create(name: "Santini", category: "Icecream and sweets", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "186")
Restaurant.create(name: "Daveroo", category: "Icecream and sweets", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "187")
Restaurant.create(name: "Amorino", category: "Icecream and sweets", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "188")
Restaurant.create(name: "Lambretta lanchonete", category: "Icecream and sweets", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "189")
Restaurant.create(name: "Casa do Gelado", category: "Icecream and sweets", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "190")

# Healthy
Restaurant.create(name: "Hora H", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "193")
Restaurant.create(name: "Cento e quatro", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "194")
Restaurant.create(name: "Gomo ", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "195")
Restaurant.create(name: "Os gazeteiros", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "196")
Restaurant.create(name: "Piadinas ", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "197")
Restaurant.create(name: "Nicolau", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "198")
Restaurant.create(name: "Dois três três", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "199")
Restaurant.create(name: "Pachamama", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "200")
Restaurant.create(name: "Club life to go", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "201")
Restaurant.create(name: "The cru (Oeiras)", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "202")
Restaurant.create(name: "Aloha Cafe", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "203")
Restaurant.create(name: "Bowl Lisboa ", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "204")
Restaurant.create(name: "A luz ideal", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "205")
Restaurant.create(name: "Organic Caffe Chiado", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "206")
Restaurant.create(name: "Montana Lisboa cafe", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "207")
Restaurant.create(name: "Naked", category: "Healthy", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "208")

# Other
Restaurant.create(name: "Duplex 💰", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "211")
Restaurant.create(name: "Alma 💰", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "212")
Restaurant.create(name: "Cantinho do avillez ", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "213")
Restaurant.create(name: "Pap' açorda", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "214")
Restaurant.create(name: "Bica do sapato 💰", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "215")
Restaurant.create(name: "Salsa e Coentros ", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "216")
Restaurant.create(name: "Belcanto 💰", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "217")
Restaurant.create(name: "Mercado c ourique ✅", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "218")
Restaurant.create(name: "Mercado ribeira ✅", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "219")
Restaurant.create(name: "Prego da peixaria ", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "220")
Restaurant.create(name: "Doca de santo", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "221")
Restaurant.create(name: "Rui dos Pregos", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "222")
Restaurant.create(name: "Valbom ", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "223")
Restaurant.create(name: "Tico tico ", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "224")
Restaurant.create(name: "Sem palavras ", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "225")
Restaurant.create(name: "Sancho ", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "226")
Restaurant.create(name: "JNcQUOI", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "227")
Restaurant.create(name: "Frutaria ", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "228")
Restaurant.create(name: "Taberna sta Marta (Marquês)", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "229")
Restaurant.create(name: "Dona Tilia (Praça de Espanha)", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "230")
Restaurant.create(name: "Taberna dos gordos", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "231")
Restaurant.create(name: "Taberna Sal grosso ", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "232")
Restaurant.create(name: "Maria Catita", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "233")
Restaurant.create(name: "Stop do bairro", category: "Other", price_range: 1, zomato_url: "", google_maps_url: "", azure_id: "234")
