# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# rails db:seed -> add seed records to database

# Italian
Restaurant.create(name: "Pizzas lux", category: "italian")
Restaurant.create(name: "Luca", category: "italian")
Restaurant.create(name: "Belalissa", category: "italian")
Restaurant.create(name: "Popolo", category: "italian")
Restaurant.create(name: "Este Oeste", category: "italian")
Restaurant.create(name: "Guilty", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Pizzaria do bairro", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "La campania", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "La finestra", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Capriciosa", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Bellezza D'Italia II", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Zero Zero", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "La trattoria", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Madpizza (Healthy pizzas)", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Osteria cucina di amici", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Mercantina", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Di casa", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Luzzo", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Máfia das pizzas (Cacilhas)", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Pasta non basta", category: "Italian", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Come prima", category: "Italian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Maritaca (Campo de Ourique; delivery)", category: "Italian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Otto", category: "Italian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Casa Al Parma", category: "Italian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "II Matriciano", category: "Italian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Polpetta - Almondegaria artesanal", category: "Italian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Este Oeste", category: "Italian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Cantina baldraca ", category: "Italian", price_range: 1, image_url: "zzzzzzz")

# Hamburgers
Restaurant.create(name: "Honorato", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Ground burguer", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz")  
Restaurant.create(name: "Buns", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "A-100", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "To-b", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Hamburgaria do Bairro ", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "McDonalds ", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Café do Rio (gourmet)", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "B Perfect ", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "The B Temple", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Hã", category: "Hamburgers", price_range: 1, image_url: "zzzzzzz")

# Sushi
Restaurant.create(name: "Sushisan", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Suntory", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Aron sushi", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Rabo de peixe", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Sea me", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Sushi factory", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Confraria ", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Miss jappa", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Yakuza", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Sushic ", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Noori ", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Kiuuby", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Nómada ", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Chirashi Sushi (bowls;Telheiras)", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "Sushi Café ", category: "Sushi", price_range: 1, image_url: "zzzzzzz") 

# Asian
Restaurant.create(name: "SOI", category: "Asian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "O Asiático", category: "Asian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "BOA BAO", category: "Asian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Tasquinha dim sum", category: "Asian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Siam Square (tailandês)", category: "Asian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pho-Pu (Vietnamita)", category: "Asian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Este Oeste", category: "Asian", price_range: 1, image_url: "zzzzzzz")

# Indian
Restaurant.create(name: "Chutnify Lisbon", category: "Indian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Indiano de telheiras", category: "Indian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Indiano de alvalade", category: "Indian", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Índia gate (Chiado)", category: "Indian", price_range: 1, image_url: "zzzzzzz")

# Seafood
Restaurant.create(name: "Rabo de peixe", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Monte mar", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Sea me", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Tasca da esquina", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pinóquio ", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "tico tico ", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Ramiro ", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Moules & beer", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Peixaria da esquina", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Doc Cod ", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pesqueiro 25 (marisco;grupos)", category: "Seafood", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pesca", category: "Seafood", price_range: 1, image_url: "zzzzzzz")

# Hotdogs
Restaurant.create(name: "Cachorraria", category: "Hotdogs", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Frankie", category: "Hotdogs", price_range: 1, image_url: "zzzzzzz")

# Tapas and snacks
Restaurant.create(name: "100 montaditos", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Topo", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Cervejaria da esquina", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Tapas bar ", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Rubro", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Boteco do largo", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Masstige", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Mesa do bairro", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "By the wine", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pharmacia ", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Matateu", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pateo do petisco (Cascais)", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Luzboa ", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Água pela Barba", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Tapisco", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Bairro do Avillez - Taberna", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Mini Bar", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Madame petisca", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Vinhos e petiscos (costa)", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Boteco do largo (jantares grupo)", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Largo ao Tacho (fado as quartas)", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Maria azeitona (Amadora)", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Travessia Bar (Cacilhas)", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "NANA petiscos (Charnecas)", category: "Tapas and Snacks", price_range: 1, image_url: "zzzzzzz")

# Steak
Restaurant.create(name: "Atalho Real", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Cafe império", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Cafe de Sao bento", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Grelhados alcantara", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "XL", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Dote", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pito do bairro", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Brasserie", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "O fondue", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Terrazza", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Butchers", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Carnalentejana", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "O Talho", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Kob", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Volver de carne y alma", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Carvoeiro de palma", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Tasca Chiado naco", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Adega das gravatas (carnide)", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Nogueira’s", category: "Steak", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "C.O.W - Beef & Cocktails", category: "Steak", price_range: 1, image_url: "zzzzzzz")

# Mexican
Restaurant.create(name: "El pibe", category: "Mexican", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "El clandestino", category: "Mexican", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Las ficheras", category: "Mexican", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pistola y corazon", category: "Mexican", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Segundo muelle", category: "Mexican", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Cheviceria", category: "Mexican", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Mez cais", category: "Mexican", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Gazpaxo", category: "Mexican", price_range: 1, image_url: "zzzzzzz")

# Peruvian Nepalese
Restaurant.create(name: "Cevicheria", category: "Peruvian or Nepalese", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Casa Nepalesa", category: "Peruvian or Nepalese", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Cantina Peruana", category: "Peruvian or Nepalese", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Segundo Muelle", category: "Peruvian or Nepalese", price_range: 1, image_url: "zzzzzzz")

# Brunch
Restaurant.create(name: "nicolau", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "fabrica dos sabores", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "brick cafe", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "O austriaco", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Choupana", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Brunch Cafe", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "The mill", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Infame (almoço também)", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "O ninho - café brunch", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Leitaria", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Delidelux", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Heim cafe", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Dear Breakfast", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Brooklyn", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "La Boulangerie", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Santo Bagel", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pão Nosso de cada dia", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: " Petit Prince Culture Cafe Lisbon", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Mercearia da Mila", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Ela canela", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Maria Limão", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "WISH slow coffee house", category: "Brunch", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "fauna e flora", category: "Brunch", price_range: 1, image_url: "zzzzzzz")

# Icecreams & Sweets
Restaurant.create(name: "Conchanata", category: "Icecream and sweets", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Baguettes & Cornets", category: "Icecream and sweets", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Nosolo Italia", category: "Icecream and sweets", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Santini", category: "Icecream and sweets", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Daveroo", category: "Icecream and sweets", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Amorino", category: "Icecream and sweets", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Lambretta lanchonete", category: "Icecream and sweets", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Casa do Gelado", category: "Icecream and sweets", price_range: 1, image_url: "zzzzzzz")

# Healthy
Restaurant.create(name: "Hora H", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Cento e quatro", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Gomo ", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Os gazeteiros", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Piadinas ", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Nicolau", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Dois três três", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pachamama", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Club life to go", category: "Healthy", price_range: 1, image_url: "zzzzzzz") 
Restaurant.create(name: "The cru (Oeiras)", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Aloha Cafe", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Bowl Lisboa ", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "A luz ideal", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Organic Caffe Chiado", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Montana Lisboa cafe", category: "Healthy", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Naked", category: "Healthy", price_range: 1, image_url: "zzzzzzz")

# Other
Restaurant.create(name: "Duplex 💰", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Alma 💰", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Cantinho do avillez ", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Pap' açorda", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Bica do sapato 💰", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Salsa e Coentros ", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Belcanto 💰", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Mercado c ourique ✅", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Mercado ribeira ✅", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Prego da peixaria ", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Doca de santo", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Rui dos Pregos", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Valbom ", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Tico tico ", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Sem palavras ", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Sancho ", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "JNcQUOI", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Frutaria ", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Taberna sta Marta (Marquês)", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Dona Tilia (Praça de Espanha)", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Taberna dos gordos", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Taberna Sal grosso ", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Maria Catita", category: "Other", price_range: 1, image_url: "zzzzzzz")
Restaurant.create(name: "Stop do bairro", category: "Other", price_range: 1, image_url: "zzzzzzz")